"""
Do not edit this file. This dynamically makes it so all modules in this folder can be loaded. To add
a new filter, you simply need to add a new .py file.
"""
from __future__ import absolute_import
from ...general.utils import load_plugins
load_plugins(__name__)
