function merge_histograms( path_ref, merged_ref_file)
% Merges 256 bin histogram txt files generated by  
% gen_histogram.m.
% The output is is a single histogram file stored
% as an ASCII text file
% 
% INPUT
% ---------
% path_ref         Directory containing text (*.txt) files of
%                  256 bin histograms
% 
% merged_ref_file  Output histogram text file.  There
%                  are 256 lines in this file 1 for each
%                  bin

  files_ref = dir(fullfile(path_ref,'*.txt'));

  %Compute summed histogram of all references
  hist_sum = zeros(256,1);
  for i = 1:numel(files_ref)
      hist_i = load(fullfile(path_ref,files_ref(i).name));
      hist_sum = hist_sum + hist_i;
  end
  save(merged_ref_file,'hist_sum','-ascii');
  fprintf('Output written to %s\n',merged_ref_file);
end

